### ISSUE TITLE
Toadflax potion (unf) does not show saradomin brew option and secondaries. 

### ISSUE THREAD

**Issue by Thommust** [TheStonedTurtle/banked-experience#102] opened 2023-01-15 19:48 UTC
Title.

Please implement, thanks! Love the plugin! :)

**Comment by TheStonedTurtle** [comment] 2023-01-15 19:52
Duplicate of #88

**Closed by TheStonedTurtle** 2023-01-15 19:52 UTC
Labels: invalid

**Comment by Thommust** [comment] 2023-02-04 21:23
I apologize; it was totally the "Respect level requirements" option
enabled. Thanks!
