### ISSUE TITLE
Carpenter outfit not updating xp needed

### ISSUE THREAD

**Issue by AmericanGoku** [TheStonedTurtle/banked-experience#82] opened 2022-06-30 18:57 UTC
When selecting the Carpenter outfit the amount of xp needed isn't updated like the other sets.  
![image](https://user-images.githubusercontent.com/80642525/176756562-77fa6aba-1630-45b5-976c-2b2d81e626dc.png)
![Screenshot 2022-06-30 135729](https://user-images.githubusercontent.com/80642525/176756687-3af8b117-0d72-4596-89f1-17bd53628d4d.png)
![Screenshot 2022-06-30 135713](https://user-images.githubusercontent.com/80642525/176756694-86d0ecfd-bc32-4014-a365-f76475942f38.png)

**Comment by DakotaCarmichael** [comment] 2022-06-30 19:00
I see this is a dupe issue, It is due to selecting Mahogany Homes as the training activity

**Comment by TheStonedTurtle** [comment] 2022-09-10 23:34
Duplicate of #53

**Closed by TheStonedTurtle** 2022-09-10 23:34 UTC
