### ISSUE TITLE
Carpenters outfit does not recalculate construction XP

### ISSUE THREAD

**Issue by DanCrayons** [TheStonedTurtle/banked-experience#68] opened 2021-12-11 21:50 UTC
When setting  your planks to Mahogany homes, clicking any piece of the construction outfit does not recalc the XP

When the planks are set to their respective product it works as expected.

**Comment by TheStonedTurtle** [comment] 2021-12-13 03:00
Duplicate of #53

**Closed by TheStonedTurtle** 2021-12-13 03:00 UTC
