### ISSUE TITLE
Nice to have: Add an option to only calculate with available secondaries.

### ISSUE THREAD

**Issue by bdjong** [TheStonedTurtle/banked-experience#127] opened 2023-11-11 10:03 UTC
Please add a setting to only include available secondaries.
This will allow to show exactly what level can be obtained with the resources you have at that moment.
It will still be nice to show how many missing so you can see that it's not the "full potential" if you'd collect the secondaries.

**Comment by bdjong** [comment] 2023-11-11 10:10
As an addition, since some materials are shared. You could perhaps limit this to herblore at first.

**Comment by TheStonedTurtle** [comment] 2023-11-24 07:31
Duplicate of #9

**Closed by TheStonedTurtle** 2023-11-24 07:31 UTC
